# 1. 빌드 이미지 (build stage)
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY backend /app
RUN chmod +x ./gradlew
RUN ./gradlew build --no-daemon --stacktrace --info

# 2. 런타임 이미지 (runtime stage)
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]