spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

    properties:
      hibernate:
        default_batch_fetch_size: 100

jwt:
  secret-key: thisissecretkeyisandeokgyun88012712859123jnqweasdpqwekjqwe
  accessToken-expiration-millis: 1_800_000
  refreshToken-expiration-mills: 1_209_600_000

cookie:
  domain: localhost
  sameSite: None
  access-token-path: /
  refresh-token-path: /

oci:
  profile: DEFAULT
  region: ${REGION}
  namespace: ${NAMESPACE}
  bucketName: ${BUCKETNAME}
  compartmentId: ${COMPARTMENTID}